/*
 * adc_config.h
 *
 * Created: 3/6/2022 12:25:45 PM
 *  Author: NourhanAlrefaei
 */ 


#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

/*
*Configure The Voltage Reference
*Range:
*ADC_VREF_AREF  
*ADC_VREF_AVCC  
*ADC_VREF_2_56V 
*/
#define ADC_VREF_SELECTOR_MSK            ADC_VREF_AVCC
#define ADC_VREF_MV                      5000
#define ADC_MAX_NUMBER_OF_STEPS          1024

/*
*Configure The ADC Mode
*Range:
*ADC_MODE_AUTO_TRIGGER     
*ADC_MODE_SINGLE_CONVERSION
*/
#define ADC_MODE_SELECTOR                ADC_MODE_SINGLE_CONVERSION


/*
*Configure ADC Adjustment
*Range:
*ADC_RIGHT_ADJUSTED
*ADC_LEFT_ADJUSTED 
*/        
#define ADC_ADJUSTMENT_SELECTOR          ADC_RIGHT_ADJUSTED

/*
*Configure ADC Prescaler
*range:
* ADC_PRESCALER_CLR_MSK
* ADC_PRESCALER_2_MSK  
* ADC_PRESCALER_4_MSK  
* ADC_PRESCALER_8_MSK  
* ADC_PRESCALER_16_MSK 
* ADC_PRESCALER_32_MSK 
* ADC_PRESCALER_64_MSK 
* ADC_PRESCALER_128_MSK
*/

#define ADC_PRESCALER_SELECTOR           ADC_PRESCALER_128_MSK

/*
*Configure ADC_Trigger_Source
*Range:
*ADC_AUTO_TRIGGER_SRC_FREE_RUNNING_MSk
*ADC_AUTO_TRIGGER_SRC_ANALOG_COMP_MSK
*ADC_AUTO_TRIGGER_SRC_EXIT0_MSK      
*ADC_AUTO_TRIGGER_SRC_TIMER0_COMP_MSK
*ADC_AUTO_TRIGGER_SRC_TIMER0_OVF_MSK 
*ADC_AUTO_TRIGGER_SRC_TIMER1_COMP_MSK
*ADC_AUTO_TRIGGER_SRC_TIMER1_OVF_MSK 
*ADC_AUTO_TRIGGER_SRC_TIMER1_CAPT_MSK
*/

#define ADC_TRIGGER_SRC_SELECTOR             ADC_AUTO_TRIGGER_SRC_FREE_RUNNING_MSK  



#endif /* ADC_CONFIG_H_ */